services:
  - type: web
    name: slate-staging
    env: elixir
    repo: https://github.com/devato/slate.git
    region: oregon
    plan: starter
    branch: develop
    buildCommand: ./rel/render-build.sh
    startCommand: _build/prod/rel/slate/bin/slate start
    healthCheckPath: /
    envVars:
    - key: SECRET_KEY_BASE
      generateValue: true
    - key: DATABASE_URL
      fromDatabase:
        name: slate-staging
        property: connectionString

databases:
  - name: slate-staging
    databaseName: slate_staging
    user: slate

# envVarGroups:
#   - name: slate-settings
#     envVars:
#     - key: CONCURRENCY
#       value: 2
#     - key: SECRET
#       generateValue: true
#     - key: USER_PROVIDED_SECRET
#       sync: false
